#ifndef POLYMER_MDMC_MACRO_HPP
#define POLYMER_MDMC_MACRO_HPP

#define GPU_PLATFORM_EXPAND_OPTION_STR(option) GPU_PLATFORM_EXPAND_OPTION_STR_(option)
#define GPU_PLATFORM_EXPAND_OPTION_STR_(option) #option

#endif // POLYMER_MDMC_MACRO_HPP
